/*
 * -----------------------------------------------------------------------------
 * input_handler.h
 *
 * Header file for the input handler module.
 *
 * This module provides functions to initialize the input and output streams
 * used by the scanner phase of the compiler.
 *
 * Functions:
 * - `Open_InputFile`:
 *      Opens the input file provided via command-line arguments or returns
 *      stdin if no file is specified.
 *
 * - `Open_OutputFile`:
 *      Creates and opens the output file used to store the list of tokens
 *      generated by the scanner, following the required ".scn" naming scheme.
 *
 * Usage:
 *     Include this header in main or scanner-related modules that require
 *     access to input/output file handling.
 *
 * Notes:
 *     Designed to be independent from the scanner logic itself.
 *
 * Author: [Isabel Expósito ]
 * -----------------------------------------------------------------------------
 */

#ifndef INPUT_HANDLER_H
#define INPUT_HANDLER_H


#include <stdio.h>



// ------------------- FUNCTIONS --------------------
FILE* Open_InputFile(int argc, char* argv[]);
FILE* Open_OutputFile(int argc, char* argv[]);
char* get_input_filename(int argc, char* argv[]);

#endif