/*
 * -----------------------------------------------------------------------------
 * input_handler.c
 *
 * This module provides functionality to manage the scanner input and output
 * files.
 *
 * - `Open_InputFile`:
 *      Opens the input file passed through command-line arguments.
 *      If no input file is provided, stdin is used.
 *      If the file cannot be opened, NULL is returned and the caller
 *      decides how to proceed.
 *
 * - `Open_OutputFile`:
 *      Creates the output file for the scanner.
 *      The output filename is generated by appending the suffix "scn"
 *      to the input filename, as required by the scanner specification.
 *      If the scanner reads from stdin, stdout is used as output.
 *
 * Usage:
 *     Called from the main program to initialize the input and output
 *     streams before starting the scanner.
 *
 * Notes:
 *     - This module strictly follows the project specification, where the
 *       input handler is responsible for creating the output file.
 *     - Memory allocated for the output filename is released internally.
 *
 *
 * Author: Isabel Expósito 
 *
 * -----------------------------------------------------------------------------
 */

#include "./input_handler_module/input_handler.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>



// ------------------- FUNCTIONS --------------------
FILE* Open_InputFile(int argc, char* argv[]) {
    if (argc > 1) {
        FILE* inputFile = fopen(argv[1], "r");
        if (!inputFile) {
            fprintf(stderr, "[INPUT_HANDLER] Error: Could not open file %s\n", argv[1]);
            return stdin;
        }
        return inputFile;
    }
    return stdin;
}


// Builds the output filename by appending the "scn" suffix to the input filename.
// Example: example.c -> example.cscn

static char* build_output_name(const char* input_name) {
    // output = input_name + "scn"
    size_t len = strlen(input_name);
    char* out = (char*)malloc(len + 4); // "scn" + '\0'
    if (!out) return NULL;

    strcpy(out, input_name);
    strcat(out, "scn");
    return out;
}


/// Opens the scanner output file according to the input arguments.
// If no input file is provided, output defaults to stdout.

FILE* Open_OutputFile(int argc, char* argv[]) {
    // If reading from stdin, output should be stdout (no filename available)
    if (argc <= 1) return stdout;

    char* outname = build_output_name(argv[1]);
    if (!outname) {
        fprintf(stderr, "[INPUT_HANDLER] Error: malloc failed creating output name\n");
        return stdout;
    }

    FILE* outputFile = fopen(outname, "w");
    if (!outputFile) {
        fprintf(stderr, "[INPUT_HANDLER] Error: Could not open output file %s\n", outname);
        free(outname);
        return stdout;
    }

    free(outname);
    return outputFile;
}

